### ISSUE TITLE
AWS Secrets Manager error: undefined method `merge' for #String

### ISSUE THREAD

**Issue by ronwsmith** [phstc/param_store#6]
Running into an issue with AWS Secrets Manager.

I have one secret with name of "secrets1" and it contains a list of keys and value pairs.

Plaintext secret looks like this:

```ruby
{
  "DATABASE_URL": "postgres://pgusername:pgpassword@stagingurl.com:5432/dbname",
  "SECRET_KEY_BASE": "sadfasdfa"
}
```

`config/application.rb`
```ruby
if %w[staging production].include?(ENV['RACK_ENV'])
  ParamStore.adapter :aws_secrets_manager, default_secret_id: "secrets1"
  ParamStore.copy_to_env('DATABASE_URL', 'SECRET_KEY_BASE', require_keys: true)
end
```

The secret is retrieved fine, but throws an error during copy_to_env:

>	 5: from /var/app/current/config/application.rb:27:in `<main>'
	 4: from /opt/rubies/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `copy_to_env'
	 3: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/param_store-1.0.0/lib/param_store/wrapper.rb:20:in `copy_to_env'
	 2: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/param_store-1.0.0/lib/param_store/wrapper.rb:44:in `cache_all'
	 1: from /opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/param_store-1.0.0/lib/param_store/adapters/secrets_manager.rb:26:in `fetch_all'
/opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/param_store-1.0.0/lib/param_store/adapters/secrets_manager.rb:26:in `inject': undefined method `merge' for #<String:0x000055dee64efe10> (NoMethodError)

Do my secrets have to be structured in a different way for this to work?

**Comment by phstc** [comment]
Hi @ronwsmith 

I'm wondering if the issue is with `default_secret_id: "secrets1"`, can you try to run 👇 ?


```ruby
ParamStore.adapter :aws_secrets_manager
ParaStore.fetch('secrets1')
ParaStore.fetch('DATABASE_URL')

ParamStore.adapter :aws_secrets_manager, default_secret_id: 'secret_id'
ParaStore.fetch('DATABASE_URL')
```

**Comment by ronwsmith** [comment]
default_secret_id seems to be working fine, see below:

```ruby
irb(main):001:0> ParamStore.adapter :aws_secrets_manager
=> #<ParamStore::Wrapper:0x0000562403b7ba88 @adapter_class=ParamStore::Adapters::SecretsManager, @opts={}>
irb(main):002:0> ParamStore.fetch("secrets1")
=> {"DATABASE_URL"=>"postgres://pgusername:pgpassword@stagingurl.com:5432/dbname", "SECRET_KEY_BASE"=>"sadfasdfa"}
irb(main):004:0> ParamStore.fetch('DATABASE_URL')
Traceback (most recent call last):
        2: from (irb):4
        1: from (irb):4:in `rescue in irb_binding'
KeyError (key not found: "DATABASE_URL")
```

```ruby
irb(main):007:0> ParamStore.adapter :aws_secrets_manager, default_secret_id: "secrets1"
=> #<ParamStore::Wrapper:0x0000562403d3f7e8 @adapter_class=ParamStore::Adapters::SecretsManager, @opts={:default_secret_id=>"secrets1"}>
irb(main):008:0> ParamStore.fetch("DATABASE_URL")
=> "postgres://pgusername:pgpassword@stagingurl.com:5432/dbname"
```

**Comment by phstc** [comment]
@ronwsmith can you bump param_store to 1.0.1 and test it again?

https://github.com/phstc/param_store/commit/0b0cd8c7fdff70bf6d4283e262169f5be8a1f982

**Comment by ronwsmith** [comment]
@phstc working now, thanks for the quick turnaround!
